### ISSUE TITLE
Sidebars 1.0.17 | Release date 11.07.2017

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson-Extensions-Approval#356]
### Changelog

* Fixed ThemeFuse/Unyson#2440

https://github.com/ThemeFuse/Unyson-Sidebars-Extension/compare/v1.0.16...v1.0.17

### Test

[Download](https://github.com/ThemeFuse/Unyson-Sidebars-Extension/releases/tag/v1.0.17) and extract in `unyson/framework/extensions/...`

**Comment by andronic90** [comment]
Problem with widgets: https://www.screencast.com/t/Obx38bb6r , please inspect before making the update

**Comment by andreiglingeanu** [comment]
Hey @andronic90 thanks for reporting that!

@GheorgheP The problem here is that `fw-reactive-options` script is [enqueued](https://github.com/ThemeFuse/Unyson/blob/v2.7.0/framework/core/components/backend.php#L423) only as a dependency of [`fw-backend-options`](https://github.com/ThemeFuse/Unyson/blob/v2.7.0/framework/core/components/backend.php#L420-L426), which probably doesn't get loaded on the Widgets Page.

The fix is quite easy.

**Comment by GheorgheP** [comment]
I will amine the Unyson release in order to solve those issues.

**Comment by andreiglingeanu** [comment]
@andronic90 Can you try [this](https://github.com/ThemeFuse/Unyson/pull/2683) fix? It should fix the issue.

**Comment by andronic90** [comment]
@andreiglingeanu Thank you, now sidebars work fine!

**Comment by andreiglingeanu** [comment]
Awesome!
